### PR TITLE
Improvements and fixes for various issues

### LINKED ISSUE #7: [rviz_tactile_plugin] contact_state display of "all taxels" is inconsistent
I tried the tactile_merger new feature to use the no_clustering
`ROS_NAMESPACE=rh rosrun tactile_merger tactile_merger _no_clustering:=true`

and used the shadow hand + its UBI tip  (used gazebo as a producer for rsp+jsp + loading the urdf). was faster for me.
`roslaunch agni_deploy hand.launch`

produced some fake data with all tactile element at maximum value of 1.0
```
rostopic pub /rh/tactile_states tactile_msgs/TactileState -s -r 10 "header:
  seq: 0
  stamp: now
  frame_id: 'rh/rh_ffdistal'
sensors: 
  - 
    name: "rh_ffdistal"
    values: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
```

to finally display this in rviz.  I expect 1 arrow per taxel, so 12 arrows.
However it is not the case and I see a different set of arrows every time I deactivate/reactivate the plugin in rviz

Screenshot_2020-10-05_13-10-27
Screenshot_2020-10-05_13-10-40

I believe the contact_states are all there see the collapsed copy-paste, but maybe adding an id at the end of the name is confusing the display ?

<details><summary>contact states rostopic ouput</summary>
<p>

```
contacts: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_0"
    position: 
      x: 0.0042
      y: -0.0062
      z: 0.0146
    normal: 
      x: 0.373828955224
      y: -0.923334188309
      z: 0.0877831927893
    wrench: 
      force: 
        x: -0.373828955224
        y: 0.923334188309
        z: -0.0877831927893
      torque: 
        x: -0.012936423354
        y: -0.00508921333655
        z: 0.00156026406851
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_1"
    position: 
      x: 0.0086
      y: 0.0005
      z: 0.0132
    normal: 
      x: 0.998969699485
      y: -0.0326779574079
      z: 0.0314911195628
    wrench: 
      force: 
        x: -0.998969699485
        y: 0.0326779574079
        z: -0.0314911195628
      torque: 
        x: -0.000447094597566
        y: -0.012915576405
        z: 0.00078051528345
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_2"
    position: 
      x: 0.0083
      y: 0.0007
      z: 0.0195
    normal: 
      x: 0.995437947817
      y: -0.0371470644981
      z: 0.0878828063107
    wrench: 
      force: 
        x: -0.995437947817
        y: 0.0371470644981
        z: -0.0878828063107
      torque: 
        x: -0.000785885722131
        y: -0.0186816126901
        z: 0.00100512719881
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_3"
    position: 
      x: 0.0035
      y: -0.005
      z: 0.0239
    normal: 
      x: 0.366010911819
      y: -0.893475408353
      z: 0.260264686615
    wrench: 
      force: 
        x: -0.366010911819
        y: 0.893475408353
        z: -0.260264686615
      torque: 
        x: -0.0200527388266
        y: -0.00783673438932
        z: 0.00129710937014
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_4"
    position: 
      x: 0.0027
      y: 0.0006
      z: 0.0303
    normal: 
      x: 0.352136494502
      y: -0.13783813449
      z: 0.925743235417
    wrench: 
      force: 
        x: -0.352136494502
        y: 0.13783813449
        z: -0.925743235417
      torque: 
        x: -0.0047319414163
        y: -0.00817022904779
        z: 0.000583444859824
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_5"
    position: 
      x: 0.0071
      y: 0.001
      z: 0.0259
    normal: 
      x: 0.923019275018
      y: -0.0631404280814
      z: 0.379537487328
    wrench: 
      force: 
        x: -0.923019275018
        y: 0.0631404280814
        z: -0.379537487328
      torque: 
        x: -0.00201487457464
        y: -0.0212114830629
        z: 0.0013713163144
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_6"
    position: 
      x: -0.0071
      y: 0.001
      z: 0.0259
    normal: 
      x: -0.923019738848
      y: -0.0631336472015
      z: 0.379537487328
    wrench: 
      force: 
        x: 0.923019738848
        y: 0.0631336472015
        z: -0.379537487328
      torque: 
        x: -0.00201469894985
        y: 0.0212114950761
        z: -0.00137126863398
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_7"
    position: 
      x: -0.0027
      y: 0.0006
      z: 0.0303
    normal: 
      x: -0.352137507108
      y: -0.137835547547
      z: 0.925743235417
    wrench: 
      force: 
        x: 0.352137507108
        y: 0.137835547547
        z: -0.925743235417
      torque: 
        x: -0.00473186303193
        y: 0.00817025972975
        z: -0.000583438482642
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_8"
    position: 
      x: -0.0035
      y: -0.005
      z: 0.0239
    normal: 
      x: -0.366017475646
      y: -0.893472719462
      z: 0.260264686615
    wrench: 
      force: 
        x: 0.366017475646
        y: 0.893472719462
        z: -0.260264686615
      torque: 
        x: -0.0200526745621
        y: 0.00783689126478
        z: -0.00129706713989
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_9"
    position: 
      x: -0.0083
      y: 0.0007
      z: 0.0195
    normal: 
      x: -0.995438220688
      y: -0.0371397516016
      z: 0.0878828063107
    wrench: 
      force: 
        x: 0.995438220688
        y: 0.0371397516016
        z: -0.0878828063107
      torque: 
        x: -0.000785743120649
        y: 0.018681618011
        z: -0.00100506669277
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_10"
    position: 
      x: -0.0086
      y: 0.0005
      z: 0.0132
    normal: 
      x: -0.998969939523
      y: -0.0326706185658
      z: 0.0314911195628
    wrench: 
      force: 
        x: 0.998969939523
        y: 0.0326706185658
        z: -0.0314911195628
      torque: 
        x: -0.00044699772485
        y: 0.0129155795735
        z: -0.000780452289428
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_11"
    position: 
      x: -0.0042
      y: -0.0062
      z: 0.0146
    normal: 
      x: -0.373835738405
      y: -0.923331441983
      z: 0.0877831927893
    wrench: 
      force: 
        x: 0.373835738405
        y: 0.923331441983
        z: -0.0877831927893
      torque: 
        x: -0.0129363832577
        y: 0.005089312371
        z: -0.00156021047822

```

</p>
</details>

### LINKED ISSUE #9: [rviz_tactile_plugin] contacts stored forever, show wrong display on clock loop
In the case of playing bag files with clock publishing and loop option, the clock jumps back in time, making the stored contacts at the end of the loop appear at the start of the loop even if there is no new data yet for those contacts.

Even worse. If there is no data published at all on contact_states in the second loop, (see video and terminal showing no data published) the simple fact that the clock loops shows past data the re-become valid for a while. 

see video [remaining_arrows_loop.mp4.zip](https://github.com/ubi-agni/tactile_toolbox/files/5335009/remaining_arrows_loop.mp4.zip)

A solution could be to clear the contact buffer if a jumbpack in time is detected.

### LINKED ISSUE #10: [rviz_tactile_plugin] False impression of missing data with "no recent msg" status
Customers reported thinking their software producing contact_states was broken, when the rviz_tactile_plugin contact_state displays reported "no recent msg" for some contact_states. 

However, it is possible that some group of taxels do not produce a contact_state, just because their tactile values are negative (until #8 is considered) or zero. This is fine and not an error, so not worth a warning.

Currently the timeout and the time of the last seen message is considered, forever. So the "no recent msg" never disappears if no new message is published for a certain group of contacts.
https://github.com/ubi-agni/tactile_toolbox/blob/melodic-devel/rviz_tactile_plugins/src/tactile_contact_display.cpp#L246

Maybe some "forgetting" about past contact_states could help ? a sort of second timeout, of 5 seconds or so, to make the contact disappear 5 seconds after the user selected timeout, while keeping the force display to be invisible directly after user selected timeout.

### PR DESCRIPTION
**Pull request by rhaschke**
- Fixes #10, by not displaying the "no recent msg" warning anymore. Wrenches silently disappear, as like point cloud points do.
- Fixes #7, by correctly initializing (and exposing) the "Hide small values" property of rviz' WrenchVisuals
- Fixes #9, resetting displays (and merger) when time is reset
- Auto-connect to tactile_contact_state(**s**) topic

### CODE REVIEW

**Comment by rhaschke** [comment]
Looks like the "Hide Small Values" property of WrenchVisuals was introduced in Melodic only. This explains that #7 suddenly popped up: The property wasn't correctly initialized in rviz.
I vote for dropping support for Kinetic.

**Comment by guihomework** [comment]
> Looks like the "Hide Small Values" property of WrenchVisuals was introduced in Melodic only. This explains that #7 suddenly popped up: The property wasn't correctly initialized in rviz.
> I vote for dropping support for Kinetic.

I did not test the new proposed solution yet, but how can the "hide small values" come into play (whether it is on or off) when all values have the same amount (I am publishing a 1.0 on all) ?

**Comment by rhaschke** [comment]
> How can the "hide small values" property come into play?

As I have written, the corresponding flag in rviz' WrenchVisual wasn't initialized and thus randomly `true` or `false`. If `true`, the arrows were hidden. What is considered `small` is [hardcoded in rviz](https://github.com/ros-visualization/rviz/blob/melodic-devel/src/rviz/default_plugin/wrench_visual.cpp#L63-L64).

Looking at that code, I'm wondering why the vectors are hidden so early... Need to double-check.

**Comment by guihomework** [comment]
> > How can the "hide small values" property come into play?
> 
> As I have written, the corresponding flag in rviz' WrenchVisual wasn't initialized and thus randomly `true` or `false`. If `true`, the arrows were hidden. What is considered `small` is [hardcoded in rviz](https://github.com/ros-visualization/rviz/blob/melodic-devel/src/rviz/default_plugin/wrench_visual.cpp#L63-L64).
> 

So you mean that even with those "quite" large arrows they were hidden; Then the problem is indeed the decision of what is "small" that came into play. 

regarding dropping support for kinetic. We have a melodic-branch, one can drop support of kinetic there I suppose.

**Comment by guihomework** [comment]
I confirm that changing the arrow width made the arrow visible even without this fix, so it is related to the way the hidesmallvalues is calculated.  I will test this branch now

**Comment by rhaschke** [comment]
Travis is finally happy as well.

File: rviz_tactile_plugins/src/tactile_contact_display.cpp [hunk 1]
```diff
@@ -235,21 +240,18 @@ void TactileContactDisplay::update(float wall_dt, float ros_dt)
 
   Display::update(wall_dt, ros_dt);
 
-  ros::Time now = ros::Time::now();
-  ros::Duration timeout(timeout_property_->getFloat());
+  ros::Time deadline = ros::Time::now() - ros::Duration(timeout_property_->getFloat());
```
Comment (guihomework) [inline rviz_tactile_plugins/src/tactile_contact_display.cpp]: I think this line is the cause of a crash when loading the plugin, and rosparam use_sim_time = true and no clock is published yet
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Time is out of dual 32-bit range
```

previous to this fix the plugin did not crash
here is the trace of the crash

```
#0  0x00007ffff60a9f47 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff60ab8b1 in __GI_abort () at abort.c:79
#2  0x00007ffff6700957 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6706ae6 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6706b21 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6706d54 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff3a77f8c in ros::normalizeSecNSecUnsigned(long&, long&) () at /opt/ros/melodic/lib/librostime.so
#7  0x00007ffff3a7d00c in ros::TimeBase<ros::Time, ros::Duration>::operator+(ros::Duration const&) const () at /opt/ros/melodic/lib/librostime.so
#8  0x00007ffff3a7d07f in ros::TimeBase<ros::Time, ros::Duration>::operator-(ros::Duration const&) const () at /opt/ros/melodic/lib/librostime.so
#9  0x00007fff93dc734a in rviz::tactile::TactileContactDisplay::update(float, float) () at /home/.../work/dev/catkin_ws_agni/devel/lib//librviz_tactile_plugins.so
#10 0x00007ffff7a7e156 in rviz::DisplayGroup::update(float, float) (this=0x5555558b5800, wall_dt=3.59348774, ros_dt=0)
    at /media/local/jenkins/jobs/rviz-agni-melodic-devel-ci-deploy-lsp-famula-nightly/workspace/src/rviz/display_group.cpp:240
#11 0x00007ffff7b48595 in rviz::VisualizationManager::onUpdate() (this=0x555556a461e0)
    at /media/local/jenkins/jobs/rviz-agni-melodic-devel-ci-deploy-lsp-famula-nightly/workspace/src/rviz/visualization_manager.cpp:361
#12 0x00007ffff6cb6555 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff6cc2fc7 in QTimer::timeout(QTimer::QPrivateSignal) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff6cc3328 in QTimer::timerEvent(QTimerEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff6cb707b in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

```

**Comment by rhaschke** [comment]
Thanks for the intense testing. Probably `sim_time` starts at zero and subtracting the timeout duration then would result in a negative deadline. Would be great if you could provide a rosbag file to test this scenario.

**Comment by rhaschke** [comment]
I fixed the offending commit, rewriting history. Could you give it another try?

**Comment by guihomework** [comment]
> Thanks for the intense testing. Probably `sim_time` starts at zero and subtracting the timeout duration then would result in a negative deadline. Would be great if you could provide a rosbag file to test this scenario.

no rosbag needed, I thought this was clear. Just start a roscore, then set rosparam set /use_sim_time true
then start rviz, load a tactile_contact_state plugin, crash.

**Comment by guihomework** [comment]
I am wondering now that this PR introduces changes on the messages and timeouts and stuff like that, could we have information, about newly incoming data, but that is immediately outdated ?
I mean contact data that has a time inferior to (now - timeout) when it arrives ? 

I ask because I fear I vaguely remember asking for such a feature in the past, and maybe the "no recent msg" was somehow there to indicate that. One should be sure before deleting it. More details follow.

what happens is that one thinks everything is ok in the contact_state plugin, but there is no display at all. I would not care about empty contact being received, or no new data when a certain contact was not refreshed for a while (which would be a "no recent msg" and I don't need that), but I care about the fact that a new data cannot be published because it is outdated before being even displayed and would like to be informed if possible.
Such an information would mean one has forgotten to set use sim time to true, and publish valid contact state in the past, 
or if the processing of contact state is too slow for instance.

Another issues related to that, is in case the tf is also outdated, in this PR, the status messages stays at "not yet published...." when data is clearly published, but tf cannot be processed

```
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[ WARN] [1602094688.843153787]: TF_OLD_DATA ignoring data from the past for frame thumb_proximal_link at time 1.60209e+09 according to authority unknown_publisher
```

**Comment by guihomework** [comment]
should I test now again with my more advanced examples ?

**Comment by rhaschke** [comment]
@guihomework, I performed a preliminary merge with melodic-devel to resolve the conflicts. If you give it the final approval, I will fast-forward melodic-devel to this PR branch.

**Comment by rhaschke** [comment]
@guihomework, you are asking a new feature (in https://github.com/ubi-agni/tactile_toolbox/pull/13#issuecomment-705113442), now that this PR is close to ready. My suggestion is that we personally discuss what you want and implement the new feature next week. I need to focus on other things for the rest of the week.

**Comment by guihomework** [comment]
> @guihomework, you are asking a new feature (in [#13 (comment)](https://github.com/ubi-agni/tactile_toolbox/pull/13#issuecomment-705113442)), now that this PR is close to ready. My suggestion is that we personally discuss what you want and implement the new feature next week. I need to focus on other things for the rest of the week.

I had to write a comment in this PR before you merge in case the feature I asked in the past WAS the "status" you removed due to Gereon's request. Maybe adapting the deletion would have been necessary. I was not certain.

Just tell that what I am talking about is not affecting this PR, that it is ok to delete the "no recent msg" and we are good.
I was not really asking for more work, delaying the merge.
On the other hand this PR solves various issues at the same time, so maybe my idea as close to the work done in this PR.

Forget what I say. I will test now.

File: tactile_merger/src/merger_node.cpp [hunk 2]
```diff
@@ -54,15 +57,28 @@ int main(int argc, char *argv[])
...
+		}
+		last_update_ = now;
+
+		if (have_new_data) {
+			have_new_data = false;
+			if (no_clustering)
+				pub.publish(merger.getAllTaxelContacts());
+			else
+				pub.publish(merger.getGroupAveragedContacts());
+			ros::spinOnce();
```
Comment (guihomework) [inline tactile_merger/src/merger_node.cpp:80]: is it standard to have two spinOnce() in a loop ? I did not find in a short research info about common practice or not.
it should be done regularly.
I mean, I guess the reason is that you want the output messages out ASAP, but this means you also get input messages stored ( in the merger handler) twice before the merger has time to use it isn't it ?

Comment (rhaschke) [reply tactile_merger/src/merger_node.cpp:80]: It's not forbidden to have two (or more) `spinOnce` calls in a loop. As you guessed, I want to have the messages processed asap. Yes, new input messages will be processed as well. But that doesn't harm. If not processed there, they would just accumulate in the message queue. With a single `spinOnce`, the time delay between receiving a tactile message and publishing a contact message might reach up to twice the loop period:
1. `spinOnce()` in the beginning of the loop:
    * `spinOnce()`: process all newly received messages and actually send the msg scheduled in _previous_ loop iteration
    * `publish()`: schedule new message for sending (based on current data)
    * `sleep()`
2. `spinOnce()` in the end of the loop:
   * `publish()`: schedule new message for sending, using data from _previous_ loop iteration
   * `spinOnce()`: process all newly received messages and _immediately_ send the scheduled msg
   * `sleep()`

Comment (rhaschke) [reply tactile_merger/src/merger_node.cpp:80]: @guihomework, as you didn't yet approve this PR: Did you observe any open issues during testing?

Comment (guihomework) [reply tactile_merger/src/merger_node.cpp:80]: >     1. `spinOnce()` in the beginning of the loop:
>        
>        * `spinOnce()`: process all newly received messages and actually send the msg scheduled in _previous_ loop iteration
>        * `publish()`: schedule new message for sending (based on current data)
>        * `sleep()`
> 
>     2. `spinOnce()` in the end of the loop:
>        
>        * `publish()`: schedule new message for sending, using data from _previous_ loop iteration
>        * `spinOnce()`: process all newly received messages and _immediately_ send the scheduled msg
>        * `sleep()`

for me this technique **could** still a problem, but not in our loop.
for me (without looking at how subscriber and spinOnce are coded), it is like the following now, (please read till the end)

* `spinOnce()` : process ONE newly received messages (called B) on the subscriber, and actually send the msg scheduled in _previous_ loop iteration that was calculated from data A
* compute average on B
* publish average on B
* `spinOnce()`: process ONE newly received messages (called C) on the subscriber, and actually send the msg scheduled in _previous_ loop iteration that was calculated from data B
* `sleep()`
* `spinOnce()`: process ONE newly received messages (called D) on the subscriber,  no new message to publish
* compute average on D (no data queue in the merger) 

so for me C was not processed **BUT**, since you have a queue of 1 in the subscriber, there will never be 2 waiting received message to store in a row within the handler, or the data was already overwritten (queue of 1).

I have a small doubt on my claim  `spinOnce()`= process ONE message, 
if my claim is wrong, that would mean that all pending incoming messages would just be handled in the handler during a `spinOnce()`, basically dropping all but the last incoming data (no data queue storage within the merger). In our loop due to 1 element in the incoming queue, the drop happens out of the `spinOnce()` anyway. 

In case we had a queue of 2 in the subscriber, what would happen ? 
if my claim i wrong and a queue > 1 in a subscriber exists, one should process the data (or queue it ourselves) directly in the subscriber callback (which I often do)

since there is no block for our special case, I can resolve the conversation

**Review by guihomework — APPROVED** [review]

File: tactile_merger/src/merger_node.cpp (hunk 2 above)
Comment (rhaschke) [reply tactile_merger/src/merger_node.cpp:80]: `spinOnce()` [processes all available messages](http://docs.ros.org/melodic/api/roscpp/html/namespaceros.html#af4afa6f0ad9f903f04a023982a95ff1c).
As we just want to publish the last received status, I think it is perfectly fine (and even desired) to drop all intermediate messages.

Comment (guihomework) [reply tactile_merger/src/merger_node.cpp:80]: > As we just want to publish the last received status, I think it is perfectly fine (and even desired) to drop all intermediate messages.

thanks for the pointer to the doc. I was more searching for usage of 2 spinOnce.
I am not blocking the merging process, but trying to understand advantages of 2 spinOnce and consequences, when using 2 is not visible so often in code.

I understand that you put the dropping of old data to the queue of size 1. fine.
so the first spinOnce gets the newest value into our local storage, the second one, sends the latest result from processing on that storage. fine
It is a special case that works.

we also have a rather constant processing time, so the published message would be regular but this is also a special case.
In a scenario where the processing time is not constant (depending on the data inside the message), sending out immediately creates jitter, when sending out after the next loop creates delay but less jitter. So the choice between 1 or 2 spinOnce is a trade off between regularity and jitter I suppose.

When doing processing and publishing within the subscriber, with one spinOnce there is also delay. 

I might have learnt a new technique here, or maybe it is a special case.
